name: deploy-testnet

on:
  push:
    branches: [feature/staking-v4]
  repository_dispatch:
    types: deploy-testnet
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: feature/staking-v4
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      - name: Setup yarn
        run: npm install -g yarn
      - run: npm config set '//npm.fontawesome.com/:_authToken' "${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}"
      - run: yarn install
      - run: yarn run prepare-pro-icons
      - run: yarn run build-testnet
        env:
          CI: false
          VITE_APP_MARKERS_API_URL: ${{ secrets.MARKERS_API_URL }}
          VITE_APP_VERSION_URL: ${{ secrets.APP_VERSION_URL }}
          VITE_APP_WALLETCONNECT_ID: ${{ secrets.WALLETCONNECT_ID }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'
      - name: Deploy to S3 bucket
        run: aws s3 sync ./build/ s3://${{ secrets.AWS_S3_BUCKET_TESTNET }} --delete
      - name: No-cache index.html
        run: aws s3 cp s3://${{ secrets.AWS_S3_BUCKET_TESTNET }}/index.html s3://${{ secrets.AWS_S3_BUCKET_TESTNET }}/index.html --metadata-directive REPLACE --cache-control max-age=0,no-cache,no-store,must-revalidate --content-type text/html --acl public-read
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_ICON_EMOJI: ':globe_with_meridians:'
          SLACK_USERNAME: ${{ secrets.AWS_S3_BUCKET_TESTNET }}
          SLACK_MESSAGE: ${{ secrets.AWS_S3_BUCKET_TESTNET }}
          SLACK_FOOTER: ''
          MSG_MINIMAL: true
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
